apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: conda-environment
spec:
  title: Anaconda Python Environment
  description: Base workshop image for Anaconda Python environment
  workshop:
    image: conda-environment:*
  session:
    resources:
      memory: 2Gi
      storage: 5Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    env:
    - name: ENABLE_JUPYTERLAB
      value: "true"
    ingresses:
    - name: jupyterlab
      port: 8888
    dashboards:
    - name: JupyterLab
      url: "$(ingress_protocol)://jupyterlab-$(session_namespace).$(ingress_domain)/"
