#@ load("@ytt:data", "data")

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: #@ "{}-cluster-admin".format(data.values.resourceNamePrefix)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: #@ "{}-operator".format(data.values.resourceNamePrefix)
  namespace: #@ data.values.namespace.name
