#@ load("@ytt:data", "data")
#@ load("config.lib.yaml", "environment_variables")

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ "{}-config".format(data.values.resourceNamePrefix)
  namespace: #@ data.values.namespace.name
data: #@ environment_variables()
