#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("@ytt:md5", "md5")
#@ load("/00-package.star", "image_reference", "image_pull_policy")
#@ load("config.lib.yaml", "environment_variables")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduk8s-operator
  namespace: #@ data.values.namespace.name
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: eduk8s-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: eduk8s-operator
      annotations:
        training.educates.dev/environment-variables: #@ md5.sum(json.encode(environment_variables()))
    spec:
      serviceAccountName: eduk8s
      containers:
      - name: eduk8s
        #@ image = image_reference("session-manager")
        image: #@ image
        imagePullPolicy: #@ image_pull_policy(image)
        envFrom:
        - configMapRef:
            name: eduk8s-config
            optional: true
