apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clientconfigs.lookup.educates.dev
spec:
  scope: Namespaced
  group: lookup.educates.dev
  names:
    plural: clientconfigs
    singular: clientconfig
    kind: ClientConfig
    categories:
      - educates-lookup
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - client
                - roles
              properties:
                client:
                  type: object
                  required:
                    - password
                  properties:
                    user:
                      type: string
                    password:
                      type: string
                      minLength: 8
                    proxy:
                      type: object
                      required:
                        - secret
                      properties:
                        issuer:
                          type: string
                          minLength: 1
                        secret:
                          type: string
                          minLength: 8
                #! Deprecated, use "spec.client.user".
                user:
                  type: string
                roles:
                  type: array
                  items:
                    type: string
                    minLength: 1
                tenants:
                  type: array
                  items:
                    type: string
                    minLength: 1
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
