apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: corsconfigs.lookup.educates.dev
spec:
  scope: Namespaced
  group: lookup.educates.dev
  names:
    plural: corsconfigs
    singular: corsconfig
    kind: CORSConfig
    categories:
      - educates-lookup
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - allowedOrigins
              properties:
                allowedOrigins:
                  type: array
                  items:
                    type: string
                    pattern: '^(\*|null|https?://.+)$'
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
