name: Pull Request
description: Use this template when creating a pull request.

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create this pull request.

        Please note that as per our contribution guidelines, unless the pull
        request is for a simple typo correction or obvious bug fix, it's
        recommended to initiate a discussion by first raising an issue. This
        enables us to assess proposed changes and evaluate whether a change to
        the core platform is really needed, or if there's a more effective
        approach to achieve the desired outcome without making the changes. 

  - type: textarea
    id: change-summary
    attributes:
      label: Summary of the changes being made by this pull request
      description: An overview of the changes you've made and why they are necessary.
    validations:
      required: true

  - type: textarea
    id: related-issues
    attributes:
      label: Related issue(s) for this pull request
      description: Link(s) to the GitHub issues this pull request is addressing.
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Add any other information related to the changes.
    validations:
      required: false
