apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.26.0

directories:
  - path: carvel-packages/cluster-essentials/bundle/config/_ytt_lib/metacontroller/_ytt_lib/upstream
    contents:
    - path: "."
      git:
        url: https://github.com/metacontroller/metacontroller
        ref: refs/tags/v4.2.0

      includePaths:
      - "manifests/production/**"

      excludePaths:
      - "**/manifests/production/kustomization.yaml"

      newRootPath: manifests/production

  - path: carvel-packages/cluster-essentials/bundle/config/_ytt_lib/kyverno/_ytt_lib/upstream
    contents:
    - path: "."
      git:
        url: https://github.com/kyverno/kyverno
        ref: refs/tags/v1.9.2

      includePaths:
      - "config/install.yaml"

      newRootPath: config

  - path: carvel-packages/cluster-essentials/bundle/config/_ytt_lib/contour/_ytt_lib/upstream
    contents:
    - path: "."
      git:
        url: https://github.com/vmware-tanzu/community-edition
        ref: origin/main

      newRootPath: addons/packages/contour/1.22.3/bundle/config

  - path: carvel-packages/training-platform/bundle/config/_ytt_lib/kyverno-restricted/_ytt_lib/upstream
    contents:
    - path: "."
      git:
        url: https://github.com/kyverno/policies
        ref: origin/release-1.9

      includePaths:
      - "pod-security/restricted/**"

      excludePaths:
      - "**/kustomization.yaml"
      - "**/kyverno-test.yaml"
      - "**/resource.yaml"

  - path: carvel-packages/training-platform/bundle/config/_ytt_lib/kyverno-baseline/_ytt_lib/upstream
    contents:
    - path: "."
      git:
        url: https://github.com/kyverno/policies
        ref: origin/release-1.9

      includePaths:
      - "pod-security/baseline/**"

      excludePaths:
      - "**/kustomization.yaml"
      - "**/kyverno-test.yaml"
      - "**/resource.yaml"

  - path: carvel-packages/training-platform/bundle/config/_ytt_lib/kyverno-policies/_ytt_lib/upstream
    contents:
    - path: "."
      git:
        url: https://github.com/kyverno/policies
        ref: origin/release-1.7

      includePaths:
      - "best-practices/disallow-empty-ingress-host/disallow_empty_ingress_host.yaml"
      - "best-practices/disallow_cri_sock_mount/disallow_cri_sock_mount.yaml"
      - "best-practices/restrict-service-external-ips/restrict-service-external-ips.yaml"
      - "best-practices/restrict_node_port/restrict_node_port.yaml"
      - "nginx-ingress/nginx-custom-snippets/disallow-custom-snippets.yaml"
      - "nginx-ingress/nginx_annotation_checks/restrict-annotations.yaml"
      - "nginx-ingress/nginx_path_checks/restrict-path.yaml"
      - "other/disallow_localhost_services/disallow_localhost_services.yaml"
      - "other/prevent-cr8escape/prevent-cr8escape.yaml"
      - "other/restrict_ingress_defaultbackend/restrict_ingress_defaultbackend.yaml"
      - "other/restrict_loadbalancer/restrict_loadbalancer.yaml"
      - "other/unique-ingress-host-and-path/unique-ingress-host-and-path.yaml"
