apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.26.0

directories:
  - path: carvel-packages/cluster-essentials/bundle/config/_ytt_lib/metacontroller/_ytt_lib/upstream
    contents:
    - path: "."
      git:
        url: https://github.com/metacontroller/metacontroller
        ref: refs/tags/v4.2.0

      includePaths:
      - "manifests/production/**"

      excludePaths:
      - "**/manifests/production/kustomization.yaml"

      newRootPath: manifests/production

  - path: carvel-packages/cluster-essentials/bundle/config/_ytt_lib/kyverno/_ytt_lib/upstream
    contents:
    - path: "."
      git:
        url: https://github.com/kyverno/kyverno
        ref: refs/tags/v1.6.2

      includePaths:
      - "config/install.yaml"

      newRootPath: config

  - path: carvel-packages/cluster-essentials/bundle/config/_ytt_lib/contour/_ytt_lib/upstream
    contents:
    - path: "."
      git:
        url: https://github.com/vmware-tanzu/community-edition
        ref: refs/tags/v0.12.1

      newRootPath: addons/packages/contour/1.20.1/bundle/config

  - path: carvel-packages/training-platform/bundle/config/_ytt_lib/kyverno-restricted/_ytt_lib/upstream
    contents:
    - path: "."
      git:
        url: https://github.com/kyverno/policies
        ref: origin/release-1.7

      excludePaths:
      - "**/kustomization.yaml"
      - "**/kyverno-test.yaml"
      - "**/resource.yaml"

      newRootPath: pod-security/restricted

  - path: carvel-packages/training-platform/bundle/config/_ytt_lib/kyverno-baseline/_ytt_lib/upstream
    contents:
    - path: "."
      git:
        url: https://github.com/kyverno/policies
        ref: origin/release-1.7

      excludePaths:
      - "**/kustomization.yaml"
      - "**/kyverno-test.yaml"
      - "**/resource.yaml"

      newRootPath: pod-security/baseline
