#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def bundle_reference():
#@   registry = data.values.imageRegistry.host
#@   if not registry or registry == "localhost:5001":
#@     registry = "registry.default.svc.cluster.local"
#@   end
#@   if data.values.imageRegistry.namespace:
#@     registry = "{}/{}".format(registry, data.values.imageRegistry.namespace)
#@   end
#@   return "{}/educates-installer:{}".format(registry, data.values.version)
#@ end

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: installer.educates.dev
spec:
  serviceAccountName: educates-installer
  fetch:
    - imgpkgBundle:
        image: #@ bundle_reference()
      path: bundle
    - inline:
        paths:
          disable-kapp-controller.yaml: |
            clusterPackages:
              kapp-controller:
                enabled: false
      path: values
  template:
    - ytt:
        valuesFrom:
          - path: "bundle/kbld/kbld-images.yaml"
          - secretRef:
              name: educates-installer
          - path: values/disable-kapp-controller.yaml
        paths:
          - "bundle/kbld/kbld-bundle.yaml"
          - "bundle/config/kapp"
          - "bundle/config/ytt"
    - kbld:
        paths:
          - "bundle/.imgpkg/images.yml"
          - "-"
  deploy:
    - kapp:
        rawOptions:
          - "--app-changes-max-to-keep=5"
          - "--diff-changes=true"
