apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eduk8s

resources:
- crds-v1beta1/workshop.yaml
- crds-v1beta1/workshop-environment.yaml
- crds-v1beta1/workshop-session.yaml
- crds-v1beta1/workshop-request.yaml
- crds-v1beta1/training-portal.yaml
- crds-v1beta1/system-profile.yaml
#- crds-v1/workshop.yaml
#- crds-v1/workshop-environment.yaml
#- crds-v1/workshop-session.yaml
#- crds-v1/workshop-request.yaml
#- crds-v1/training-portal.yaml
#- crds-v1/system-profile.yaml
- resources/operator/namespace.yaml
- resources/operator/serviceaccount.yaml
- resources/operator/rolebinding.yaml
- resources/operator/deployment.yaml
