apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: jupyter-environment
spec:
  title: Jupyter Environment
  description: Base workshop image for Jupyter environment.
  content:
    image: quay.io/eduk8s/jupyter-environment:master
  session:
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    ingresses:
    - name: jupyter
      port: 8888
    dashboards:
    - name: Jupyter
      url: "$(ingress_protocol)://$(session_namespace)-jupyter.$(ingress_domain)/"
    patches:
     containers:
     - name: workshop
       resources:
         requests:
           memory: 1Gi
         limits:
           memory: 1Gi
       volumeMounts:
       - name: data
         mountPath: /home/eduk8s
     volumes:
     - name: data
       persistentVolumeClaim:
         claimName: $(session_namespace)-data
    objects:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        namespace: $(workshop_namespace)
        name: $(session_namespace)-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
