#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:library", "library")

#@ clusterpolicies = library.get("kyverno-policies").eval()

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ "{}-config".format(data.values.operator.namePrefix)
  namespace: #@ data.values.operator.namespace
  annotations:
    kapp.k14s.io/versioned: ""
    kapp.k14s.io/num-versions: "5"
#@ if data.values.clusterIngress.domain == "educates-local-dev.xyz":
stringData:
  values.yaml: #@ yaml.encode(data.values)
  clusterpolicies.yaml: #@ yaml.encode(clusterpolicies)
#@ else:
data:
  values.yaml: #@ base64.encode(yaml.encode(data.values))
  clusterpolicies.yaml: #@ yaml.encode(clusterpolicies)
#@ end

#@ ingress_certificate = getattr(data.values.clusterIngress.tlsCertificate, "tls.crt")
#@ ingress_private_key = getattr(data.values.clusterIngress.tlsCertificate, "tls.key")
#@ ingress_secret_ref_name = data.values.clusterIngress.tlsCertificateRef.name

---
#@ if not ingress_secret_ref_name and ingress_certificate and ingress_private_key:
apiVersion: v1
kind: Secret
metadata:
  name: #@ "{}-tls".format(data.values.clusterIngress.domain)
  namespace: #@ data.values.operator.namespace
type: kubernetes.io/tls
data:
  tls.crt: #@ base64.encode(ingress_certificate)
  tls.key: #@ base64.encode(ingress_private_key)
#@ end
