name: Bug Report
description: Use this template when creating a bug report.
labels:
- bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is, including steps to reproduce it and the expected behaviour.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Add any other information such as version details for Educates, Kubernetes, Docker and the host operating system.
    validations:
      required: false
