name: Feature Request
description: Use this template when creating a feature request.
labels:
- enhancement

body:
  - type: textarea
    id: describe-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: describe-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: describe-alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Add any other information relevant to the feature request here.
    validations:
      required: false
