#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

#@ ingress_certificate = getattr(data.values.tlsCertificate, "tls.crt")
#@ ingress_private_key = getattr(data.values.tlsCertificate, "tls.key")
#@ ingress_secret_ref_name = data.values.tlsCertificateRef.name

---
#@ if not ingress_secret_ref_name and ingress_certificate and ingress_private_key:
apiVersion: v1
kind: Secret
metadata:
  name: #@ "{}-tls".format(data.values.ingressDomain)
  namespace: #@ data.values.namespace.name
type: kubernetes.io/tls
data:
  tls.crt: #@ base64.encode(ingress_certificate)
  tls.key: #@ base64.encode(ingress_private_key)
#@ end
