apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cluster-essentials.educates.dev.2.6.8
spec:
  refName: cluster-essentials.educates.dev
  version: 2.6.8
  releasedAt: "2023-09-08T08:51:22Z"
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        clusterPackages:
          type: object
          additionalProperties: false
          properties:
            contour:
              type: object
              additionalProperties: false
              properties:
                enabled:
                  type: boolean
                  default: true
                settings:
                  nullable: true
                  default: {}
            kyverno:
              type: object
              additionalProperties: false
              properties:
                enabled:
                  type: boolean
                  default: true
                settings:
                  nullable: true
                  default: {}
            metacontroller:
              type: object
              additionalProperties: false
              properties:
                enabled:
                  type: boolean
                  default: false
                settings:
                  nullable: true
                  default: {}
        clusterInfrastructure:
          type: object
          additionalProperties: false
          properties:
            provider:
              type: string
              default: ""
        clusterSecurity:
          type: object
          additionalProperties: false
          properties:
            policyEngine:
              type: string
              default: none
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/vmware-tanzu-labs/educates-cluster-essentials:2.6.8
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp:
          rawOptions:
          - --app-changes-max-to-keep=5
