#! ServiceAccount for remote access clients.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: remote-access
  namespace: educates
  annotations:
    kapp.k14s.io/change-group: "educates/sa-with-separate-token-secret"
