#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"Ingress"})
---
metadata:
  #@overlay/match missing_ok=True
  #@ if/end data.values.certName:
  annotations:
   ingress.kubernetes.io/force-ssl-redirect: "true"
   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
   nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  #@overlay/match missing_ok=True
  #@ if/end data.values.ingressClass:
  ingressClassName: #@ data.values.ingressClass
  rules:
  #@overlay/match by=overlay.index(0)
  - host: #@ data.values.tld
  #@overlay/match missing_ok=True
  #@ if/end data.values.certName:
  tls:
  - hosts:
    - #@ data.values.tld
    secretName: #@ data.values.certName
