#! Cluster role for the remote access clients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: educates-remote-access
rules:
  - apiGroups:
      - training.educates.dev
    resources:
      - trainingportals
      - workshopenvironments
      - workshopsessions
      - workshopallocations
      - workshops
    verbs:
      - get
      - list
      - watch
