#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")

#@ for name in data.values.clusterPackages:
#@ package = data.values.clusterPackages[name]
#@ if package.enabled:
--- #@ template.replace(library.get(name).with_data_values(data.values, plain=True).eval())
#@ end
#@ end
