apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workshopenvironments.training.eduk8s.io
spec:
  scope: Cluster
  group: training.eduk8s.io
  names:
    plural: workshopenvironments
    singular: workshopenvironment
    kind: WorkshopEnvironment
    categories:
    - eduk8s
    - eduk8s-training
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            workshop:
              type: object
              required:
              - name
              properties:
                name:
                  type: string
            request:
              type: object
              properties:
                token:
                  type: string
                namespaces:
                  type: array
                  items:
                    type: string
            session:
              type: object
              required:
              properties:
                username:
                  type: string
                password:
                  type: string
                domain:
                  type: string
                env:
                  type: array
                  items:
                    type: object
                    required:
                    - name
                    properties:
                      name:
                        type: string
                      value:
                        type: string
        status:
          type: object
          properties:
            environment_create:
              type: object
              properties:
                namespace:
                  type: string
                workshop:
                  type: object
  additionalPrinterColumns:
  - name: Namespace
    type: string
    priority: 0
    description: The namespace in which the workshop is deployed.
    JSONPath: .status.environment_create.namespace
  - name: Image
    type: string
    priority: 0
    description: The image used to deploy the workshop.
    JSONPath: .status.environment_create.workshop.image
