apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: trainingportals.training.eduk8s.io
spec:
  scope: Cluster
  group: training.eduk8s.io
  names:
    plural: trainingportals
    singular: trainingportal
    kind: TrainingPortal
    categories:
    - eduk8s
    - eduk8s-training
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            portal:
              type: object
              required:
              - capacity
              properties:
                domain:
                  type: string
                password:
                  type: string
                capacity:
                  type: integer
            workshops:
              type: array
              items:
                type: object
                required:
                - name
                properties:
                  name:
                    type: string
                  env:
                    type: array
                    items:
                      type: object
                      required:
                      - name
                      properties:
                        name:
                          type: string
                        value:
                          type: string
        status:
          type: object
          properties:
            eduk8s:
              type: object
              required:
              - url
              properties:
                url:
                  type: string
  additionalPrinterColumns:
  - name: URL
    type: string
    priority: 0
    description: The URL for accessing the portal.
    JSONPath: .status.eduk8s.url
  - name: Password
    type: string
    priority: 0
    description: The password for accessing the portal.
    JSONPath: .status.eduk8s.password
