apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workshops.training.eduk8s.io
spec:
  scope: Cluster
  group: training.eduk8s.io
  names:
    plural: workshops
    singular: workshop
    kind: Workshop
    categories:
    - eduk8s
    - eduk8s-training
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
          - vendor
          - title
          - description
          - image
          properties:
            vendor:
              type: string
            title:
              type: string
            description:
              type: string
            url:
              type: string
            image:
              type: string
            duration:
              type: string
              pattern: '^\d+(s|m|h)$'
            workshop:
              type: object
              properties:
                objects:
                  type: array
                  items:
                    type: object
            session:
              type: object
              properties:
                role:
                  type: string
                budget:
                  type: string
                env:
                  type: array
                  items:
                    type: object
                    required:
                    - name
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                ingress:
                  type: array
                  items:
                    type: object
                    required:
                    - name
                    properties:
                      name:
                        type: string
                      port:
                        type: integer
                patches:
                  type: object
                objects:
                  type: array
                  items:
                    type: object
        status:
          type: object
  additionalPrinterColumns:
  - name: Image
    type: string
    priority: 0
    description: The location of the image for the workshop.
    JSONPath: .spec.image
  - name: URL
    type: string
    priority: 0
    description: URL for further information on the workshop.
    JSONPath: .spec.url
