apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sessions.training.eduk8s.io
spec:
  scope: Cluster
  group: training.eduk8s.io
  names:
    plural: sessions
    singular: session
    kind: Session
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - userID
              - workshop
              properties:
                userID:
                  type: string
                workshop:
                  type: string
                username:
                  type: string
                password:
                  type: string
                hostname:
                  type: string
                domain:
                  type: string
                env:
                  type: array
                  items:
                    type: object
                    required:
                    - name
                    properties:
                      name:
                        type: string
                      value:
                        type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                session_create:
                  type: object
                  properties:
                    namespace:
                      type: string
                    image:
                      type: string
      additionalPrinterColumns:
      - name: Namespace
        type: string
        priority: 0
        description: The namespace in which the workshop is deployed.
        jsonPath: .status.session_create.namespace
      - name: Image
        type: string
        priority: 0
        description: The image used to deploy the workshop.
        jsonPath: .status.session_create.image
