apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workspaces.training.eduk8s.io
spec:
  scope: Namespaced
  group: training.eduk8s.io
  names:
    plural: workspaces
    singular: workspace
    kind: Workspace
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - workshop
              properties:
                workshop:
                  type: string
                username:
                  type: string
                password:
                  type: string
                domain:
                  type: string
                env:
                  type: array
                  items:
                    type: object
                    required:
                    - name
                    properties:
                      name:
                        type: string
                      value:
                        type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                workspace_create:
                  type: object
                  properties:
                    namespace:
                      type: string
                    workshop:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
      - name: Namespace
        type: string
        priority: 0
        description: The namespace in which the workshop is deployed.
        jsonPath: .status.workspace_create.namespace
      - name: Image
        type: string
        priority: 0
        description: The image used to deploy the workshop.
        jsonPath: .status.workspace_create.workshop.image
