#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("educates.lib.yaml", "copy_core_educates_values")

#! This copies only core Educates values.

#@overlay/match-child-defaults missing_ok=True
clusterPackages:
  educates:
    settings: #@ copy_core_educates_values()
