#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:base64", "base64")

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ "{}-config".format(data.values.resourceNamePrefix)
  namespace: #@ data.values.namespace.name
  annotations:
    kapp.k14s.io/versioned: ""
    kapp.k14s.io/num-versions: "5"
#@ if data.values.ingressDomain == "local.educates.dev":
stringData:
  values.yaml: #@ yaml.encode(data.values)
#@ else:
data:
  values.yaml: #@ base64.encode(data.values)
#@ end
