#@ load("@ytt:data", "data")
#@ load("/00-package.star", "image_pull_secrets")

---
apiVersion: #@ "training.{}/v1alpha1".format(data.values.operatorApiGroup)
kind: SystemProfile
metadata:
  name: default-system-profile
spec:
  #@ if data.values.storageClass or data.values.storageUser or data.values.storageGroup:
  storage:
    #@ if data.values.storageClass:
    class: #@ data.values.storageClass
    #@ end
    #@ if data.values.storageUser:
    user: #@ int(data.values.storageUser)
    #@ end
    #@ if data.values.storageGroup:
    group: #@ int(data.values.storageGroup)
    #@ end
  #@ end
  dockerd:
    #@ if data.values.dockerDaemon.networkMTU:
    mtu: #@ data.values.dockerDaemon.networkMTU
    #@ end
    rootless: #@ data.values.dockerDaemon.rootless
    #@ if data.values.dockerDaemon.proxyCache.remoteURL:
    mirror:
      remote: #@ data.values.dockerDaemon.proxyCache.remoteURL
      #@ if data.values.dockerDaemon.proxyCache.username:
      username: #@ data.values.dockerDaemon.proxyCache.username
      password: #@ data.values.dockerDaemon.proxyCache.password or ""
      #@ end
    #@ end
  portal:
    credentials:
      admin:
        #@ if data.values.portalCredentials.systemAdmin.username:
        username: #@ data.values.portalCredentials.systemAdmin.username
        #@ end
        #@ if data.values.portalCredentials.systemAdmin.password:
        password: #@ data.values.portalCredentials.systemAdmin.password
        #@ end
      robot:
        #@ if data.values.portalCredentials.clientAccess.username:
        username: #@ data.values.portalCredentials.clientAccess.username
        #@ end
        #@ if data.values.portalCredentials.clientAccess.password:
        password: #@ data.values.portalCredentials.clientAccess.password
        #@ end
  network:
    blockCIDRs: #@ data.values.clusterNetwork.blockCIDRs
  analytics:
    #@ if data.values.workshopAnalytics.google:
    google: #@ data.values.workshopAnalytics.google
    #@ end
