#@ load("@ytt:data", "data")
#@ load("/00-package.star", "image_pull_secrets")

#@ pull_secrets = image_pull_secrets()
#@ if pull_secrets:
---
apiVersion: #@ "secrets.{}/v1alpha1".format(data.values.operatorApiGroup)
kind: SecretInjector
metadata:
  name: #@ "{}-image-pull-secrets".format(data.values.resourceNamePrefix)
spec:
  rules:
  - targetNamespaces:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operatorApiGroup) @): portal
    sourceSecrets:
      nameSelector:
        matchNames: #@ pull_secrets
    serviceAccounts:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operatorApiGroup) @): portal
  - targetNamespaces:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operatorApiGroup) @): environment
    sourceSecrets:
      nameSelector:
        matchNames: #@ pull_secrets
    serviceAccounts:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operatorApiGroup) @): environment
  - targetNamespaces:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operatorApiGroup) @): environment
    sourceSecrets:
      nameSelector:
        matchNames: #@ pull_secrets
    serviceAccounts:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operatorApiGroup) @): session
#@ end
