#@ load("@ytt:data", "data")
#@ load("/00-package.star", "image_pull_secrets")

#@ ingress_secret_ref_name = data.values.tlsCertificateRef.name
#@ ingress_secret_ref_namespace = data.values.tlsCertificateRef.namespace

#@ if ingress_secret_ref_name and ingress_secret_ref_namespace and ingress_secret_ref_namespace != data.values.namespace.name:
---
apiVersion: #@ "secrets.{}/v1alpha1".format(data.values.operatorApiGroup)
kind: SecretCopier
metadata:
  name: #@ "{}-upstream-ingress-secret".format(data.values.resourceNamePrefix)
spec:
  rules:
  - sourceSecret:
      name: #@ ingress_secret_ref_name
      namespace: #@ ingress_secret_ref_namespace
    targetNamespaces:
      nameSelector:
        matchNames:
        - #@ data.values.namespace.name
---
apiVersion: #@ "secrets.{}/v1alpha1".format(data.values.operatorApiGroup)
kind: SecretCopier
metadata:
  name: #@ "{}-downstream-ingress-secret".format(data.values.resourceNamePrefix)
spec:
  rules:
  - sourceSecret:
      name: #@ ingress_secret_ref_name
      namespace: #@ data.values.namespace.name
    targetNamespaces:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operatorApiGroup) @): portal
  - sourceSecret:
      name: #@ ingress_secret_ref_name
      namespace: #@ data.values.namespace.name
    targetNamespaces:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operatorApiGroup) @): environment
#@ end

#@ secrets = []
#@ for secret in data.values.imagePullSecretRefs:
#@   if secret["namespace"] and secret["namespace"] != data.values.namespace.name:
#@     secrets.append(secret)
#@   end
#@ end
#@ if secrets:
---
apiVersion: #@ "secrets.{}/v1alpha1".format(data.values.operatorApiGroup)
kind: SecretCopier
metadata:
  name: #@ "{}-upstream-image-pull-secrets".format(data.values.resourceNamePrefix)
spec:
  rules:
  #@ for secret in secrets:
  - sourceSecret:
      name: #@ secret["name"]
      namespace: #@ secret["namespace"]
    targetNamespaces:
      nameSelector:
        matchNames:
        - #@ data.values.namespace.name
  #@ end
#@ end

#@ pull_secrets = image_pull_secrets()
#@ if pull_secrets:
---
apiVersion: #@ "secrets.{}/v1alpha1".format(data.values.operatorApiGroup)
kind: SecretCopier
metadata:
  name: #@ "{}-downstream-image-pull-secrets".format(data.values.resourceNamePrefix)
spec:
  rules:
  #@ for name in pull_secrets:
  - sourceSecret:
      name: #@ name
      namespace: #@ data.values.namespace.name
    targetNamespaces:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operatorApiGroup) @): portal
  - sourceSecret:
      name: #@ name
      namespace: #@ data.values.namespace.name
    targetNamespaces:
      labelSelector:
        matchLabels:
          #@yaml/text-templated-strings
          (@= "training.{}/component".format(data.values.operatorApiGroup) @): environment
  #@ end
#@ end
