#@ load("@ytt:data", "data")
#@ load("/00-package.star", "image_reference")

#@ ingress_secret_name = None
#@ ingress_certificate = getattr(data.values.tlsCertificate, "tls.crt")
#@ ingress_private_key = getattr(data.values.tlsCertificate, "tls.key")
#@ ingress_secret_ref_name = data.values.tlsCertificateRef.name
#@ ingress_secret_ref_namespace = data.values.tlsCertificateRef.namespace
#@ if not ingress_secret_ref_name and ingress_certificate and ingress_private_key:
#@   ingress_secret_name = "{}/{}-tls".format(data.values.namespace.name, data.values.ingressDomain)
#@ elif ingress_secret_ref_name:
#@   ingress_secret_name = "{}/{}".format(data.values.namespace.name, ingress_secret_ref_name)
#@ end

#@ def environment_variables():
SYSTEM_PROFILE: default-system-profile
OPERATOR_API_GROUP: #@ data.values.operatorApiGroup
RESOURCE_STATUS_KEY: #@ data.values.resourceStatusKey
RESOURCE_NAME_PREFIX: #@ data.values.resourceNamePrefix
INGRESS_DOMAIN: #@ data.values.ingressDomain
#@ if ingress_secret_name:
INGRESS_SECRET: #@ ingress_secret_name
#@ end
#@ if data.values.ingressClass:
INGRESS_CLASS: #@ data.values.ingressClass
#@ end
SESSION_MANAGER_IMAGE: #@ image_reference("session-manager")
TRAINING_PORTAL_IMAGE: #@ image_reference("training-portal")
DOCKER_IN_DOCKER_IMAGE: #@ image_reference("docker-in-docker")
DOCKER_REGISTRY_IMAGE: #@ image_reference("docker-registry")
PAUSE_CONTAINER_IMAGE: #@ image_reference("pause-container")
BASE_ENVIRONMENT_IMAGE: #@ image_reference("base-environment")
JDK8_ENVIRONMENT_IMAGE: #@ image_reference("jdk8-environment")
JDK11_ENVIRONMENT_IMAGE: #@ image_reference("jdk11-environment")
CONDA_ENVIRONMENT_IMAGE: #@ image_reference("conda-environment")
#@ end
