#@ load("@ytt:data", "data")

#@ def image_reference(name):
#@   registry = data.values.imageRegistry.host
#@   if not registry or registry == "localhost:5001":
#@     registry = "registry.default.svc.cluster.local:5001"
#@   end
#@   if data.values.imageRegistry.namespace:
#@     registry = "{}/{}".format(registry, data.values.imageRegistry.namespace)
#@   end
#@   return "{}/educates-{}:{}".format(registry, name, data.values.version)
#@ end

---
imageVersions:
- name: session-manager
  image: #@ image_reference("session-manager")
- name: training-portal
  image: #@ image_reference("training-portal")
- name: docker-registry
  image: #@ image_reference("docker-registry")
- name: pause-container
  image: #@ image_reference("pause-container")
- name: base-environment
  image: #@ image_reference("base-environment")
- name: jdk8-environment
  image: #@ image_reference("jdk8-environment")
- name: jdk11-environment
  image: #@ image_reference("jdk11-environment")
- name: jdk17-environment
  image: #@ image_reference("jdk17-environment")
- name: conda-environment
  image: #@ image_reference("conda-environment")
- name: secrets-manager
  image: #@ image_reference("secrets-manager")
- name: docker-in-docker
  image: "docker:20.10.18-dind"
- name: rancher-k3s
  image: "rancher/k3s:v1.25.3-k3s1"
- name: loftsh-vcluster
  image: "loftsh/vcluster:0.13.0"
- name: contour-bundle
  #! contour.community.tanzu.vmware.com.1.20.1 
  image: projects.registry.vmware.com/tce/contour@sha256:0128c3458d57cd637c198b3a6377bb1eca6e23301f27710ac29d9d0ee1c5bd09
