apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
  - paths:
      - [type]
    type: copy
    sources: [existing, new]
    resourceMatchers:
      - apiVersionKindMatcher: { apiVersion: v1, kind: Secret }
  # - paths:
  #     - [data]
  #     - [metadata,annotations,"kubernetes.io/service-account.uid"]
  #     - [metadata,annotations,"kubernetes.io/service-account.name"]
  #     - [type]
  #   type: copy
  #   sources: [existing, new]
  #   resourceMatchers:
  #     - andMatcher:
  #         matchers:
  #           - apiVersionKindMatcher: { apiVersion: v1, kind: Secret }
  #           - hasAnnotationMatcher:
  #               keys: 
  #                 - "kubernetes.io/service-account.name"