#@ load("@ytt:data", "data")

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: packages.educates.dev
spec:
  fetch:
    imgpkgBundle:
      image: #@ "{}/educates-packages:{}".format(data.values.packageRepository, data.values.repositoryVersion)
