apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: systemprofiles.training.eduk8s.io
spec:
  scope: Cluster
  group: training.eduk8s.io
  names:
    plural: systemprofiles
    singular: systemprofile
    kind: SystemProfile
    categories:
    - eduk8s
    - eduk8s-training
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ingress:
                  type: object
                  properties:
                    domain:
                      type: string
                    secret:
                      type: string
                    class:
                      type: string
                environment:
                  type: object
                  properties:
                    secrets:
                      type: object
                      properties:
                        pull:
                          type: array
                          items:
                            type: string
