apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trainingportals.training.eduk8s.io
spec:
  scope: Cluster
  group: training.eduk8s.io
  names:
    plural: trainingportals
    singular: trainingportal
    kind: TrainingPortal
    categories:
    - eduk8s
    - eduk8s-training
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                portal:
                  type: object
                  required:
                  - capacity
                  properties:
                    domain:
                      type: string
                    capacity:
                      type: integer
                workshops:
                  type: array
                  items:
                    type: object
                    required:
                    - name
                    properties:
                      name:
                        type: string
                      env:
                        type: array
                        items:
                          type: object
                          required:
                          - name
                          properties:
                            name:
                              type: string
                            value:
                              type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                eduk8s:
                  type: object
                  required:
                  - url
                  - credentials
                  - environments
                  properties:
                    url:
                      type: string
                    credentials:
                      type: object
                      required:
                      - administrator
                      properties:
                        administrator:
                          type: string
                    workshops:
                      type: array
                      items:
                        type: object
                        required:
                        - name
                        - vendor
                        - title
                        - description
                        - url
                        properties:
                          name:
                            type: string
                          vendor:
                            type: string
                          title:
                            type: string
                          description:
                            type: string
                          url:
                            type: string
                    environments:
                      type: array
                      items:
                        type: object
                        required:
                        - name
                        - workshop
                        - sessions
                        properties:
                          name:
                            type: string
                          workshop:
                            type: object
                            required:
                            - name
                            properties:
                              name:
                                type: string
                          sessions:
                            type: array
                            items:
                              type: object
                              required:
                              - name
                              - id
                              - username
                              - password
                              - hostname
                              properties:
                                name:
                                  type: string
                                id:
                                  type: string
                                username:
                                  type: string
                                password:
                                  type: string
                                hostname:
                                  type: string
      additionalPrinterColumns:
      - name: URL
        type: string
        priority: 0
        description: The URL for accessing the portal.
        jsonPath: .status.eduk8s.url
      - name: AdministratorPassword
        type: string
        priority: 0
        description: The password for accessing admin pages.
        jsonPath: .status.eduk8s.credentials.administrator
