#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: session-manager
  namespace: #@ data.values.operator.namespace

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-puller
  namespace: #@ data.values.operator.namespace
