name: Build and Publish Images

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+"

jobs:
  publish-generic-images:
    name: Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: docker-in-docker
          - image: docker-registry
          - image: pause-container
          - image: session-manager
          - image: training-portal

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate container image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{github.repository_owner}}/educates-${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push ${{ matrix.image }} image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.image }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
