name: Build and Publish Images

on:
  push:
    branches:
      - "**"
    tags:
      - "[0-9]+.[0-9]+"

jobs:
  build-and-publish-images:
    name: Build and publish images
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    strategy:
      matrix:
       include:
         - image: docker-in-docker
           context: docker-in-docker
         - image: docker-registry
           context: docker-registry
         - image: pause-container
           context: pause-container

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Restore docker-in-docker image
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-${{ matrix.image }}
          key: ${{ runner.os }}-buildx-${{ matrix.image }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.image }}-

      - name: Build ${{ matrix.image }} image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          tags: localhost:5000/educates-${{ matrix.image }}:latest
          cache-from: type=local,src=/tmp/.buildx-${{ matrix.image }}
          cache-to: type=local,dest=/tmp/.buildx-${{ matrix.image }}-new
          push: true

      - name: Save ${{ matrix.image }} cache
        run: |
          rm -rf /tmp/.buildx-${{ matrix.image }}
          mv /tmp/.buildx-${{ matrix.image }}-new /tmp/.buildx-${{ matrix.image }}
