name: Build and Publish Images

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+"

jobs:
  build-and-publish-images:
    name: Build and publish images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: docker-in-docker
            context: docker-in-docker
          - image: docker-registry
            context: docker-registry
          - image: pause-container
            context: pause-container

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate container image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{github.repository_owner}}/educates-${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}

      - name: Build and push ${{ matrix.image }} image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
