---
apiVersion: kbld.k14s.io/v1alpha1
minimumRequiredVersion: 0.30.0
kind: Config
searchRules:
  - keyMatcher:
      name: config.yaml
    updateStrategy:
      yaml:
        searchRules:
        - keyMatcher:
            name: image
  - keyMatcher:
      name: values.yaml
    updateStrategy:
      yaml:
        searchRules:
        - keyMatcher:
            name: image
  # This rule replaces acmeresolver image in cert-manager deployment (after upstream descriptor has been modified by educates installer)
  - keyMatcher:
      name: acmesolver-image
